version: '3'

services:
  front:
    build: front_end/
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'

  back:
    build: api/
    depends_on:
      - 'database'
    ports:
      - '1000:1000'

  database:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword

